{{- if and .Values.keycloak.enabled .Values.appAdmin.email .Values.appAdmin.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-virtual-agent.fullname" . }}-app-admin
  labels:
    {{- include "ai-virtual-agent.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
stringData:
  app-admin-password: {{ .Values.appAdmin.password | quote }}
{{- end }}
