---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "ai-virtual-agent.fullname" . }}-env
  labels:
    {{- include "ai-virtual-agent.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.runners.langgraph.llm_api_key }}
  LANGGRAPH_LLM_API_KEY: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.runners.crewai.llm_api_key }}
  CREWAI_LLM_API_KEY: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.apiKeys.tavily }}
  TAVILY_API_KEY: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.apiKeys.serpapi }}
  SERPAPI_API_KEY: {{ . | b64enc | quote }}
  {{- end }}
