"""add_runner_type_to_virtual_agents

Revision ID: ba58d1b9cea2
Revises: 1b936f86b868
Create Date: 2026-02-12 05:13:14.888879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba58d1b9cea2'
down_revision: Union[str, None] = '1b936f86b868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'virtual_agents',
        sa.Column(
            'runner_type',
            sa.String(length=50),
            server_default='llamastack',
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtual_agents', 'runner_type')
    # ### end Alembic commands ###
